### ISSUE TITLE
ciao

### ISSUE THREAD

**Issue by melottimarco** [jojo2234/Human-Method#2]
Ciao ,  come posso contattarti in privato?
@jojo2234

**Comment by jojo2234** [comment]
Ciao, questi sono i miei contatti: twitter: @loberry96 Instagram: @loberry96.

Se la discussione riguarda la mia precedente ricerca che trovi qui aggiornata: https://mega.nz/file/ps4y0LTa#e7CNvm_WH3sAFvMn4FCg9VAhFz2AscHv2kEBkCFzmlw

Può essere utile sapere che è stata conclusa e sono giunto alla conclusione che non è possibile creare un Green Pass auto-generato valido. Per via del fatto che servirebbe una chiave privata valida impossibile da ottenere.
